language: python
python: '3.4'
install:
  - pip install -r requirements.txt
  - gem install mdl
script:
  - mdl -s markdownlint-rules.rb .
  - mkdocs build
  - ./link_validator.py
after_success:
  - >-
    if ! [[ "${TRAVIS_PULL_REQUEST}" = "false"  && "${TRAVIS_BRANCH}" = "master" ]]; then exit 0; fi
  - git remote add deploy https://${GH_TOKEN}@github.com/OpenIndiana/oi-docs.git
  - git config user.name "Travis CI Build"
  - git fetch deploy && git fetch deploy gh-pages:gh-pages
  - mkdocs gh-deploy -v --clean --remote-name deploy --remote-branch gh-pages
env:
  global:
    - secure: >-
        zF1Z4JFXrK0YQzBq2WRMqvwIp+M8cKO8KQZX+IILYuvxWQrdVu0blVGX2fIziZNkWa+CXRJ74oo5Ub5Vn15XBn2iofchbYC96rBdMZTOwsbE2X6U40mEBuoBKdsck0xiQ1myDvrlZTtfC8XuSQb4nl67dIyJ3zt46/eQ7I1qn123dt9t9fY04hRgRGqBx8gg+UtMtyftL+HI83lFM/3OTk3f7uFPYU6W5sTnrwUzGMbpoyiecI+qQ8oiiYbcf8x+cW9kqNx0QZUkHZ/FMufmfyKeME71YQnOJ85yM1T4vTbt0cqa1RyaSB2GT5T+W0Y1ErSZZTd+PC/y74ABzUN9mhoXe6Go9mwHDAUR0+GBjwSJrgjMyg8EjjfF1XSGG0Se7IV0ZkjL+2cBd6mAyvpSiZ3ZAHrKqKcDqJZX3aeUYXW46wFoLpoYoGuKt05bt3AE12yMwBOBZJhd6sEi4RtqjBftsKAOnt9cwtEqlM3t/mOk10Y+7jieSFxFiJSVuDFAmT+33m6HF4OlhCYtmu2YYl6zj0KgGB28Sud5M5nRA5WE+dA9CfdxcBa008jviT3Xibw8wSAnSyqEgc3Og8J1wIow7JJETRvK4aDtaFmOb2hbk44xj+v2vN5ln+g0D68YtAb0HJOIpC6PPQTkUTaLYxBvwhtNIa+eTvZgTfP/Kvo=
