# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at https://illumos.org/license/
# 
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at https://illumos.org/license/
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END

#
# Copyright 2021 J. Madgwick.  All rights reserved.
#

lang: en
author-meta: The OpenIndiana Project
numbersections: false
colorlinks: true
classoption:
- oneside
geometry:
- lmargin=25mm
- rmargin=25mm
- tmargin=30mm
- bmargin=24mm
fontsize: 11pt
header-includes:
 - \usepackage{fvextra,fancyhdr,changepage,sectsty,tocloft,titling}
#Solbook/Dockbook Style Header & Footer
 - \pagestyle{fancy}
 - \fancyhead{}
 - \fancyfoot{}\renewcommand{\footrulewidth}{0.4pt}\fancyfoot[CEO]{\thepage}
#Ensure verbatim code blocks have line breaks and do not overflow the page
 - \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,breakanywhere,commandchars=\\\{\}}
 - \DefineVerbatimEnvironment{verbatim}{Verbatim}{breaklines,breakanywhere}
#Solbook/Dockbook style Fonts
 - \setmainfont{Liberation Serif}
 - \setmonofont[Scale=0.8]{Liberation Mono}
 - \newfontfamily\symbolfont[]{Noto Sans Symbols2}
#Solbook/Dockbook style Headings
 - \newfontfamily\headingfont[UprightFont={* Bold}]{Liberation Sans}
 - \sectionfont{\Huge\headingfont}\subsectionfont{\huge\headingfont}
#Solbook/Dockbook style TOC and Title Page
 - \setcounter{tocdepth}{2}
 - \renewcommand{\cftsecdotsep}{\cftdotsep}\renewcommand{\cftdotsep}{2.5}
 - \renewcommand{\cftbeforesecskip}{0.1em}
 - \addtocontents{toc}{\small}
 - \addtolength{\cftsecindent}{5.5em}\addtolength{\cftsubsecindent}{6em}
 - \renewcommand{\maketitlehooka}{\headingfont}
 - \renewcommand{\cfttoctitlefont}{\headingfont\Huge}
